name: s4
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.3.0

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+4  # Adicionando dependência para SQLite
  path: ^1.8.0       # Necessário para gerenciar os caminhos do banco de dados local

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/src/assets/images/
flutter_assets:
  assets_path: lib/src/assets/images/
  output_path: lib/dist/
  filename: assets.dart